// Copyright (C) 2026 Juan Jose Perez Sanchez — 2J Fitness Center
// SPDX-License-Identifier: AGPL-3.0-or-later
/* Coverage matrix of the official 2J guided routines — "Entrena con 2J" (Guided Routines V1).
 *
 * A guided routine is a complete, ready-to-start workout; a block is one piece of a workout.
 * Every routine here is COMPOSED of official blocks (scripts/protocol/official-blocks.matrix.mjs)
 * — warm-up, main part, cool-down — and never lists exercises of its own. The build
 * (scripts/build-official-routines.mjs) copies each block in as a versioned snapshot (the same
 * instantiateBlock the builder uses), validates the whole routine under the 2J protocol, checks
 * diversity, and writes api/lib/guided-official.json.
 *
 * Human-reviewable on purpose. Why these families (a product decision, not science):
 *   Tabata-format and HIIT for short conditioning; circuits for strength-endurance on the gym's
 *   machines, dumbbells or no equipment; cardio intervals on the machines 2J has; mobility for
 *   before/after training and specific areas; a few mixed strength + cardio sessions; core.
 *   Levels only where the session really changes (moves, density, coordination) — no clones.
 *
 * Text (name, subtitle, description) is an English source string rendered through t() — the
 * Spanish lives in frontend/src/locales/es.js like every other UI string.
 *
 * Row fields: id, category, name, subtitle, description, goal, level, focus, parts[[role, blockId]],
 * lowImpact? (curated; the build verifies no jumps and no running in it).
 */
const W = 'off-fullbody-general-beginner-a-mobility'          // activation: ankles, knees, chest · standing · ~3 min
const W_LEGS = 'off-lower-general-beginner-b-mobility'         // lower-body activation
const COOL = 'off-fullbody-general-beginner-x-mobility'        // standing cool-down flow
const RECOVER = 'off-fullbody-general-beginner-b-mobility'     // floor recovery

export const ROUTINES = [
  // ───────── TABATA FORMAT (20 s / 10 s)
  { id: 'r2j-tabata-start', category: 'tabata', name: 'Tabata · First steps', subtitle: 'No jumps · no equipment',
    description: 'Your first 20/10 intervals: steps and wall high knees, easy to keep clean.', goal: 'general', level: 'beginner', focus: 'fullbody',
    parts: [['warmup', W], ['main', 'off-fullbody-general-beginner-a-hiit']], lowImpact: true },
  { id: 'r2j-tabata-nojumps', category: 'tabata', name: 'Tabata · No jumps', subtitle: 'Three blocks, whole body',
    description: 'Twelve minutes of 20/10 work for legs, chest and the whole body without a single jump.', goal: 'general', level: 'intermediate', focus: 'fullbody',
    parts: [['warmup', W], ['main', 'off-fullbody-general-beginner-a-hiit'], ['main', 'off-lower-general-beginner-a-hiit'], ['main', 'off-upper-general-intermediate-x-hiit']], lowImpact: true },
  { id: 'r2j-tabata-fullbody', category: 'tabata', name: 'Tabata · Full body', subtitle: 'Burpees, jumps and core',
    description: 'The classic 20/10 format across the whole body: a demanding session in under twenty minutes.', goal: 'general', level: 'intermediate', focus: 'fullbody',
    parts: [['warmup', W], ['main', 'off-fullbody-general-intermediate-a-hiit'], ['main', 'off-lower-general-intermediate-a-hiit'], ['main', 'off-abs-general-intermediate-a-hiit']] },
  { id: 'r2j-tabata-lower', category: 'tabata', name: 'Tabata · Lower body', subtitle: 'Squats, lunges and bridges',
    description: 'Two 20/10 blocks for legs and glutes after a short lower-body activation.', goal: 'general', level: 'intermediate', focus: 'lower',
    parts: [['warmup', W_LEGS], ['main', 'off-lower-general-intermediate-a-hiit'], ['main', 'off-lower-general-beginner-a-hiit']] },
  { id: 'r2j-tabata-core', category: 'tabata', name: 'Tabata · Core', subtitle: 'Two blocks · floor',
    description: 'Flutter kicks, Russian twists, plank taps and climbers in 20/10.', goal: 'general', level: 'intermediate', focus: 'core',
    parts: [['warmup', W], ['main', 'off-abs-general-intermediate-a-hiit'], ['main', 'off-abs-general-intermediate-b-hiit']] },
  { id: 'r2j-tabata-bike', category: 'tabata', name: 'Tabata · Bike', subtitle: '20/10 × 8 on the bike',
    description: 'Eight 20-second efforts on the stationary bike with 10 seconds easy between them.', goal: 'general', level: 'advanced', focus: 'cardio',
    parts: [['warmup', W], ['main', 'off-cardio-general-advanced-x-hiit'], ['cooldown', COOL]], lowImpact: true },
  { id: 'r2j-tabata-elliptical', category: 'tabata', name: 'Tabata · Elliptical', subtitle: '20/10 × 8 · low impact',
    description: 'The 20/10 format on the elliptical: hard efforts without impact on the joints.', goal: 'general', level: 'intermediate', focus: 'cardio',
    parts: [['warmup', W], ['main', 'off-cardio-general-intermediate-x-hiit'], ['cooldown', COOL]], lowImpact: true },
  { id: 'r2j-tabata-advanced', category: 'tabata', name: 'Tabata · Advanced', subtitle: 'Four blocks · jumps',
    description: 'Four 20/10 blocks with burpees, skater hops, jacks and jump squats. For people who already know the format.', goal: 'general', level: 'advanced', focus: 'fullbody',
    parts: [['warmup', W], ['main', 'off-fullbody-general-advanced-a-hiit'], ['main', 'off-fullbody-general-intermediate-b-hiit'], ['main', 'off-lower-general-intermediate-a-hiit'], ['main', 'off-abs-general-intermediate-b-hiit']] },

  // ───────── HIIT (own work/rest per block)
  { id: 'r2j-hiit-lowimpact', category: 'hiit', name: 'HIIT · Low impact', subtitle: '30 s on / 30 s off',
    description: 'Steps, wall high knees, incline push-ups and plank taps. Intense without jumping.', goal: 'general', level: 'beginner', focus: 'fullbody',
    parts: [['warmup', W], ['main', 'off-fullbody-general-beginner-b-hiit'], ['cooldown', COOL]], lowImpact: true },
  { id: 'r2j-hiit-fullbody', category: 'hiit', name: 'HIIT · Full body', subtitle: '40 s on / 20 s off',
    description: 'Jump squats, climbers, skater hops and push-ups: three rounds with a minute between them.', goal: 'general', level: 'intermediate', focus: 'fullbody',
    parts: [['warmup', W], ['main', 'off-fullbody-general-intermediate-c-hiit'], ['cooldown', COOL]] },
  { id: 'r2j-hiit-express', category: 'hiit', name: 'HIIT · Express with dumbbells', subtitle: 'Strength moves on the clock',
    description: 'Goblet squats and presses mixed with climbers and steps, 40/20 for three rounds.', goal: 'general', level: 'intermediate', focus: 'fullbody',
    parts: [['warmup', W], ['main', 'off-fullbody-general-intermediate-d-hiit']] },
  { id: 'r2j-hiit-lower', category: 'hiit', name: 'HIIT · Lower body, no jumps', subtitle: 'Lunges, bridges, high knees',
    description: 'Hard lower-body intervals without jumping, finished with hip mobility on the floor.', goal: 'general', level: 'intermediate', focus: 'lower',
    parts: [['warmup', W_LEGS], ['main', 'off-lower-general-intermediate-b-hiit'], ['cooldown', 'off-lower-general-beginner-c-mobility']], lowImpact: true },
  { id: 'r2j-hiit-advanced', category: 'hiit', name: 'HIIT · Advanced', subtitle: '45 s on / 15 s off × 4',
    description: 'Burpees, bear crawls, jump squats and plank taps with short rests, then core and a floor cool-down.', goal: 'general', level: 'advanced', focus: 'fullbody',
    parts: [['warmup', W], ['main', 'off-fullbody-general-advanced-b-hiit'], ['main', 'off-abs-general-intermediate-a-hiit'], ['cooldown', RECOVER]] },
  { id: 'r2j-hiit-machines', category: 'hiit', name: 'HIIT · Two machines', subtitle: 'Elliptical, then bike',
    description: 'Two 20/10 blocks: eight efforts on the elliptical and eight on the bike.', goal: 'general', level: 'advanced', focus: 'cardio',
    parts: [['warmup', W], ['main', 'off-cardio-general-intermediate-x-hiit'], ['main', 'off-cardio-general-advanced-x-hiit'], ['cooldown', COOL]], lowImpact: true },

  // ───────── CIRCUITS
  { id: 'r2j-circuit-machines-start', category: 'circuit', name: 'Circuit · Machines, first steps', subtitle: 'Guided machines · 3 rounds',
    description: 'Leg press, chest press, pulldown and leg curl by reps, with a side plank. A safe way into circuits.', goal: 'general', level: 'beginner', focus: 'fullbody',
    parts: [['warmup', W], ['main', 'off-fullbody-general-beginner-x-circuit'], ['cooldown', 'off-fullbody-general-beginner-x-mobility']] },
  { id: 'r2j-circuit-machines-time', category: 'circuit', name: 'Circuit · Machines against the clock', subtitle: '40 s per machine',
    description: 'Five machines, forty seconds each, three rounds. Steady, controlled work.', goal: 'endurance', level: 'beginner', focus: 'fullbody',
    parts: [['warmup', W], ['main', 'off-fullbody-endurance-beginner-x-circuit']] },
  { id: 'r2j-circuit-dumbbells', category: 'circuit', name: 'Circuit · Dumbbells, full body', subtitle: 'Squat, press, row, hinge',
    description: 'A full-body circuit with dumbbells by reps and a timed plank to close each round.', goal: 'general', level: 'intermediate', focus: 'fullbody',
    parts: [['warmup', W], ['main', 'off-fullbody-general-intermediate-a-circuit'], ['cooldown', COOL]] },
  { id: 'r2j-circuit-bodyweight', category: 'circuit', name: 'Circuit · No equipment', subtitle: 'Bodyweight · 2 rounds',
    description: 'Split squats, incline push-ups, bridges, a kneeling plank and ski steps. Only your body.', goal: 'endurance', level: 'beginner', focus: 'fullbody',
    parts: [['warmup', W], ['main', 'off-fullbody-endurance-beginner-a-circuit']] },
  { id: 'r2j-circuit-lower', category: 'circuit', name: 'Circuit · Lower body', subtitle: 'Reps and timed bridges',
    description: 'Split squats, Romanian deadlifts, marching bridges and calf raises, then hip mobility.', goal: 'endurance', level: 'intermediate', focus: 'lower',
    parts: [['warmup', W_LEGS], ['main', 'off-lower-endurance-intermediate-x-circuit'], ['cooldown', 'off-lower-general-beginner-c-mobility']] },
  { id: 'r2j-circuit-upper', category: 'circuit', name: 'Circuit · Upper body', subtitle: 'Push, pull, press, arms',
    description: 'Five upper-body stations for three rounds, then shoulder mobility.', goal: 'endurance', level: 'intermediate', focus: 'upper',
    parts: [['warmup', W], ['main', 'off-upper-endurance-intermediate-x-circuit'], ['cooldown', 'off-shoulders-general-beginner-x-mobility']] },
  { id: 'r2j-circuit-advanced', category: 'circuit', name: 'Circuit · Advanced full body', subtitle: 'Dumbbells, push-ups, crawls',
    description: 'A dense full-body circuit mixing reps and timed conditioning, with a floor cool-down.', goal: 'endurance', level: 'advanced', focus: 'fullbody',
    parts: [['warmup', W], ['main', 'off-fullbody-endurance-advanced-x-circuit'], ['cooldown', RECOVER]] },

  // ───────── STRENGTH + CARDIO
  { id: 'r2j-mixed-circuit-hiit', category: 'mixed', name: 'Strength + cardio · Circuit and HIIT', subtitle: 'Machines, then dumbbells on the clock',
    description: 'A machine circuit with cardio bursts, followed by a dumbbell HIIT block.', goal: 'general', level: 'intermediate', focus: 'fullbody',
    parts: [['warmup', W], ['main', 'off-fullbody-general-intermediate-b-circuit'], ['main', 'off-fullbody-general-intermediate-d-hiit']] },
  { id: 'r2j-mixed-strength-intervals', category: 'mixed', name: 'Strength + cardio · Full body and bike', subtitle: 'Straight sets, then intervals',
    description: 'A full-body strength block with prescribed rest, then easy bike intervals to finish.', goal: 'general', level: 'intermediate', focus: 'fullbody',
    parts: [['warmup', W], ['main', 'off-fullbody-general-intermediate-b'], ['main', 'off-cardio-general-beginner-x-interval']] },

  // ───────── CORE
  { id: 'r2j-core-start', category: 'core', name: 'Core · First steps', subtitle: 'Floor · 2 rounds',
    description: 'Dead bugs, a kneeling plank, side planks and crunches: a short, controlled core session.', goal: 'general', level: 'beginner', focus: 'core',
    parts: [['warmup', W], ['main', 'off-abs-general-beginner-x-circuit']] },
  { id: 'r2j-core-circuit', category: 'core', name: 'Core · Circuit', subtitle: 'Cable, plank, side plank',
    description: 'Cable crunches and dead bugs by reps, planks against the clock, three rounds.', goal: 'general', level: 'intermediate', focus: 'core',
    parts: [['warmup', W], ['main', 'off-abs-general-intermediate-x-circuit']] },

  // ───────── CARDIO INTERVALS
  { id: 'r2j-intervals-bike-start', category: 'interval', name: 'Intervals · Bike, first steps', subtitle: '1 min on / 1 min easy',
    description: 'Six one-minute efforts on the bike with a minute easy between them.', goal: 'general', level: 'beginner', focus: 'cardio',
    parts: [['warmup', W], ['main', 'off-cardio-general-beginner-x-interval'], ['cooldown', COOL]], lowImpact: true },
  { id: 'r2j-intervals-incline-walk', category: 'interval', name: 'Intervals · Incline walk', subtitle: '3 min on / 1 min easy',
    description: 'Four three-minute blocks of brisk incline walking on the treadmill.', goal: 'endurance', level: 'beginner', focus: 'cardio',
    parts: [['warmup', W], ['main', 'off-cardio-endurance-beginner-x-interval']], lowImpact: true },
  { id: 'r2j-intervals-elliptical', category: 'interval', name: 'Intervals · Elliptical', subtitle: '1 min on / 1 min easy',
    description: 'Six one-minute pushes on the elliptical, easy recovery between them.', goal: 'general', level: 'intermediate', focus: 'cardio',
    parts: [['warmup', W], ['main', 'off-cardio-general-intermediate-x-interval'], ['cooldown', COOL]], lowImpact: true },
  { id: 'r2j-intervals-stepmill', category: 'interval', name: 'Intervals · Stepmill', subtitle: '2 min on / 1 min easy',
    description: 'Five two-minute climbs on the stepmill.', goal: 'endurance', level: 'intermediate', focus: 'cardio',
    parts: [['warmup', W], ['main', 'off-cardio-endurance-intermediate-x-interval'], ['cooldown', COOL]], lowImpact: true },
  { id: 'r2j-intervals-treadmill', category: 'interval', name: 'Intervals · Treadmill, short', subtitle: '30 s fast / 90 s easy',
    description: 'Eight short, fast runs on the treadmill with long easy recoveries.', goal: 'general', level: 'advanced', focus: 'cardio',
    parts: [['warmup', W], ['main', 'off-cardio-general-advanced-x-interval'], ['cooldown', COOL]] },
  { id: 'r2j-intervals-cross-long', category: 'interval', name: 'Intervals · Cross trainer, long', subtitle: '4 min on / 2 min easy',
    description: 'Four long efforts on the cross trainer for sustained work.', goal: 'endurance', level: 'advanced', focus: 'cardio',
    parts: [['warmup', W], ['main', 'off-cardio-endurance-advanced-x-interval'], ['cooldown', COOL]], lowImpact: true },

  // ───────── MOBILITY (moving better; never treatment)
  { id: 'r2j-mobility-fullbody', category: 'mobility', name: 'Mobility · Full body', subtitle: 'Standing, then floor',
    description: 'A standing flow from hips to shoulders, then hips and hamstrings on the floor.', goal: 'general', level: 'beginner', focus: 'fullbody',
    parts: [['main', 'off-fullbody-general-beginner-x-mobility'], ['main', 'off-lower-general-beginner-c-mobility']], lowImpact: true },
  { id: 'r2j-mobility-hips', category: 'mobility', name: 'Mobility · Hips', subtitle: 'Floor and standing',
    description: 'Glutes, hamstrings and hip rotation on the floor, then hips and quads standing.', goal: 'general', level: 'beginner', focus: 'lower',
    parts: [['main', 'off-lower-general-beginner-c-mobility'], ['main', 'off-lower-general-beginner-a-mobility']], lowImpact: true },
  { id: 'r2j-mobility-ankles', category: 'mobility', name: 'Mobility · Ankles and calves', subtitle: 'Standing · express',
    description: 'Ankle and knee circles and two calf stretches.', goal: 'general', level: 'beginner', focus: 'lower',
    parts: [['main', 'off-calves-general-beginner-x-mobility']], lowImpact: true },
  { id: 'r2j-mobility-shoulders', category: 'mobility', name: 'Mobility · Shoulders', subtitle: 'Standing · 2 rounds',
    description: 'Chest opener, front and back of the shoulder, and lats against a bench.', goal: 'general', level: 'beginner', focus: 'upper',
    parts: [['main', 'off-shoulders-general-beginner-x-mobility']], lowImpact: true },
  { id: 'r2j-mobility-upper-back', category: 'mobility', name: 'Mobility · Upper back', subtitle: 'Standing and seated',
    description: 'Upper-back and side stretches, then a seated twist and reach.', goal: 'general', level: 'beginner', focus: 'upper',
    parts: [['main', 'off-upper-general-beginner-x-mobility']], lowImpact: true },
  { id: 'r2j-mobility-pre', category: 'mobility', name: 'Mobility · Before training', subtitle: 'Activation + hips',
    description: 'A standing activation from feet to shoulders, then hips, before you lift.', goal: 'general', level: 'beginner', focus: 'fullbody',
    parts: [['main', W], ['main', 'off-lower-general-beginner-a-mobility']], lowImpact: true },
  { id: 'r2j-mobility-post', category: 'mobility', name: 'Mobility · After training', subtitle: 'Easy · floor',
    description: 'Slow floor stretches for legs, hips and back, then calves and ankles.', goal: 'general', level: 'beginner', focus: 'fullbody',
    parts: [['main', RECOVER], ['main', 'off-calves-general-beginner-x-mobility']], lowImpact: true },
  { id: 'r2j-mobility-express', category: 'mobility', name: 'Mobility · Express', subtitle: 'Four moves, standing',
    description: 'A quick standing reset: lunge stretch, chest opener, ankles and side stretch.', goal: 'general', level: 'intermediate', focus: 'fullbody',
    parts: [['main', 'off-fullbody-general-intermediate-x-mobility']], lowImpact: true },

  // Every new session below uses an existing, protocol-checked block. The strength sessions
  // keep their prescribed sets and rest; they are not repackaged as timed circuits.
  { id: 'r2j-strength-return-a', category: 'strength', name: 'Return · Stable full body', subtitle: 'Machines · controlled sets', description: 'Leg press, chest press, back and core with generous rest.', goal: 'beginner', level: 'beginner', focus: 'fullbody', parts: [['main', 'off-fullbody-beginner-beginner-a']] },
  { id: 'r2j-strength-return-b', category: 'strength', name: 'Return · Free movement', subtitle: 'Dumbbells and stable support', description: 'A second first-week session with a different squat, push and pull.', goal: 'beginner', level: 'beginner', focus: 'fullbody', parts: [['main', 'off-fullbody-beginner-beginner-b']] },
  { id: 'r2j-strength-home-full', category: 'strength', name: 'Home · Full body', subtitle: 'Dumbbells and bodyweight', description: 'A compact full-body session with basic free-weight movements.', goal: 'general', level: 'beginner', focus: 'fullbody', parts: [['main', 'off-fullbody-general-beginner-c']] },
  { id: 'r2j-strength-fullbody-a', category: 'strength', name: 'Full body · Hypertrophy A', subtitle: 'Squat, push and pull', description: 'A balanced muscle-building day across the whole body.', goal: 'hypertrophy', level: 'intermediate', focus: 'fullbody', parts: [['main', 'off-fullbody-hypertrophy-intermediate-a']] },
  { id: 'r2j-strength-fullbody-b', category: 'strength', name: 'Full body · Hypertrophy B', subtitle: 'Different angles and implements', description: 'A complementary full-body day with a different exercise selection.', goal: 'hypertrophy', level: 'intermediate', focus: 'fullbody', parts: [['main', 'off-fullbody-hypertrophy-intermediate-b']] },
  { id: 'r2j-strength-upper-a', category: 'strength', name: 'Upper · Push and pull A', subtitle: 'Chest, back and shoulders', description: 'Upper-body hypertrophy with straight sets and full rests.', goal: 'hypertrophy', level: 'intermediate', focus: 'upper', parts: [['main', 'off-upper-hypertrophy-intermediate-x-ss']] },
  { id: 'r2j-strength-upper-b', category: 'strength', name: 'Upper · Base', subtitle: 'Push, pull and arms', description: 'An approachable upper-body session using stable machines.', goal: 'general', level: 'beginner', focus: 'upper', parts: [['main', 'off-upper-general-beginner-x']] },
  { id: 'r2j-strength-lower-a', category: 'strength', name: 'Lower · Hypertrophy A', subtitle: 'Quad and posterior chain', description: 'A complete leg day with controlled sets and prescribed rest.', goal: 'hypertrophy', level: 'intermediate', focus: 'lower', parts: [['main', 'off-lower-hypertrophy-intermediate-a']] },
  { id: 'r2j-strength-lower-b', category: 'strength', name: 'Lower · Hypertrophy B', subtitle: 'Different leg emphasis', description: 'A complementary lower-body day using different implements.', goal: 'hypertrophy', level: 'intermediate', focus: 'lower', parts: [['main', 'off-lower-hypertrophy-intermediate-b']] },
  { id: 'r2j-strength-push-a', category: 'strength', name: 'Push · Hypertrophy A', subtitle: 'Chest, shoulders, triceps', description: 'The push day of a three-day split with straight sets.', goal: 'hypertrophy', level: 'intermediate', focus: 'upper', parts: [['main', 'off-push-hypertrophy-intermediate-a']] },
  { id: 'r2j-strength-push-b', category: 'strength', name: 'Push · Hypertrophy B', subtitle: 'Alternate pressing angles', description: 'A second push day for variety across weeks.', goal: 'hypertrophy', level: 'intermediate', focus: 'upper', parts: [['main', 'off-push-hypertrophy-intermediate-b']] },
  { id: 'r2j-strength-pull-a', category: 'strength', name: 'Pull · Hypertrophy A', subtitle: 'Back and biceps', description: 'Horizontal and vertical pulls before smaller arm work.', goal: 'hypertrophy', level: 'intermediate', focus: 'upper', parts: [['main', 'off-pull-hypertrophy-intermediate-a']] },
  { id: 'r2j-strength-pull-b', category: 'strength', name: 'Pull · Hypertrophy B', subtitle: 'Alternate pull selection', description: 'A second pull day with different equipment and angles.', goal: 'hypertrophy', level: 'intermediate', focus: 'upper', parts: [['main', 'off-pull-hypertrophy-intermediate-b']] },
  { id: 'r2j-strength-glutes-a', category: 'strength', name: 'Glutes · Foundation', subtitle: 'Bridge, squat and hinge', description: 'A stable lower-body session with extra glute emphasis.', goal: 'hypertrophy', level: 'beginner', focus: 'lower', parts: [['main', 'off-glutes-hypertrophy-beginner-a']] },
  { id: 'r2j-strength-glutes-b', category: 'strength', name: 'Glutes · Progression', subtitle: 'Different glute angles', description: 'A complementary glute day with free weights and machines.', goal: 'hypertrophy', level: 'intermediate', focus: 'lower', parts: [['main', 'off-glutes-hypertrophy-intermediate-b']] },
  { id: 'r2j-strength-base-full', category: 'strength', name: 'Strength base · Full body', subtitle: 'Main lifts first', description: 'A squat, press and row day with longer rests and lower reps.', goal: 'strength', level: 'intermediate', focus: 'fullbody', parts: [['main', 'off-fullbody-strength-intermediate-x']] },
  { id: 'r2j-strength-base-lower', category: 'strength', name: 'Strength base · Lower', subtitle: 'Squat and hinge', description: 'Lower-body strength with a clear main lift and accessory work.', goal: 'strength', level: 'intermediate', focus: 'lower', parts: [['main', 'off-lower-strength-intermediate-x']] },
  { id: 'r2j-strength-base-upper', category: 'strength', name: 'Strength base · Press', subtitle: 'Bench and support work', description: 'A pressing strength day using the existing prescribed rests.', goal: 'strength', level: 'intermediate', focus: 'upper', parts: [['main', 'off-chest-strength-intermediate-x']] },
  { id: 'r2j-strength-back', category: 'strength', name: 'Back · Hypertrophy', subtitle: 'Rows and vertical pulls', description: 'A focused back session with stable, varied pulling.', goal: 'hypertrophy', level: 'intermediate', focus: 'upper', parts: [['main', 'off-back-hypertrophy-intermediate-c']] },
  { id: 'r2j-strength-shoulders', category: 'strength', name: 'Shoulders · Hypertrophy', subtitle: 'Press and raises', description: 'A focused shoulder session with controlled straight sets.', goal: 'hypertrophy', level: 'intermediate', focus: 'upper', parts: [['main', 'off-shoulders-hypertrophy-intermediate-c']] },
  { id: 'r2j-strength-core-base', category: 'core', name: 'Core · Strength base', subtitle: 'Plank, flexion and rotation', description: 'Three controlled movements with rests, not a speed challenge.', goal: 'general', level: 'intermediate', focus: 'core', parts: [['main', 'off-abs-general-intermediate-x']] },
  { id: 'r2j-strength-core-advanced', category: 'core', name: 'Core · Advanced strength', subtitle: 'Loaded and hanging work', description: 'A demanding core session for people with established control.', goal: 'general', level: 'advanced', focus: 'core', parts: [['main', 'off-abs-general-advanced-x']] },
  { id: 'r2j-mobility-recovery', category: 'mobility', name: 'Mobility · Recovery day', subtitle: 'Gentle standing and floor flow', description: 'An easy sequence for a day between harder sessions.', goal: 'general', level: 'beginner', focus: 'fullbody', parts: [['main', 'off-fullbody-general-beginner-b-mobility'], ['main', 'off-shoulders-general-beginner-x-mobility']], lowImpact: true },
  { id: 'r2j-mobility-upper', category: 'mobility', name: 'Stretch · Upper body', subtitle: 'Shoulders and back', description: 'An upper-body stretch flow after training.', goal: 'general', level: 'beginner', focus: 'upper', parts: [['main', 'off-shoulders-general-beginner-x-mobility'], ['main', 'off-upper-general-beginner-x-mobility']], lowImpact: true },
  { id: 'r2j-mobility-posterior', category: 'mobility', name: 'Stretch · Posterior chain', subtitle: 'Hamstrings, calves and back', description: 'Easy posterior-chain stretches without forcing range.', goal: 'general', level: 'beginner', focus: 'lower', parts: [['main', 'off-lower-general-beginner-c-mobility'], ['main', 'off-upper-general-beginner-x-mobility']], lowImpact: true },
  { id: 'r2j-mobility-wrists', category: 'mobility', name: 'Mobility · Wrists', subtitle: 'Circles and gentle stretch', description: 'A short wrist flow before gripping or pressing.', goal: 'general', level: 'beginner', focus: 'upper', parts: [['main', 'off-upper-general-beginner-a-mobility']], lowImpact: true },
  { id: 'r2j-mobility-adductors', category: 'mobility', name: 'Mobility · Adductors', subtitle: 'Seated hip opening', description: 'Two floor stretches for the inner thighs within a comfortable range.', goal: 'general', level: 'beginner', focus: 'lower', parts: [['main', 'off-lower-general-beginner-d-mobility']], lowImpact: true },
  { id: 'r2j-mobility-thoracic', category: 'mobility', name: 'Mobility · Thoracic spine', subtitle: 'Standing and seated', description: 'Upper-back extension, rotation and a gentle chest opener.', goal: 'general', level: 'beginner', focus: 'upper', parts: [['main', 'off-upper-general-beginner-b-mobility']], lowImpact: true },
  { id: 'r2j-hiit-bodyweight', category: 'hiit', name: 'HIIT · Bodyweight only', subtitle: 'No machines', description: 'Three bodyweight interval blocks with distinct lower, upper and core demands.', goal: 'general', level: 'intermediate', focus: 'fullbody', parts: [['warmup', W], ['main', 'off-lower-general-intermediate-b-hiit'], ['main', 'off-upper-general-intermediate-x-hiit'], ['main', 'off-abs-general-intermediate-a-hiit']] },
  { id: 'r2j-tabata-mixed', category: 'tabata', name: 'Tabata · Mixed emphasis', subtitle: 'Lower, upper and core', description: 'Three different 20/10 blocks with breaks between emphases.', goal: 'general', level: 'intermediate', focus: 'fullbody', parts: [['warmup', W], ['main', 'off-lower-general-intermediate-a-hiit'], ['main', 'off-upper-general-intermediate-x-hiit'], ['main', 'off-abs-general-intermediate-a-hiit']] },
  // ───────── ENTRENA CON 2J ADMIN SPRINT — content expansion: warm-ups, cool-downs, stretching, recovery, machine HIIT/Tabata/intervals, strength splits, mixed sessions.
  { id: 'r2j-warmup-upper', category: 'mobility', purpose: 'warmup', name: 'Warm-up · Upper body', subtitle: 'Scapulae, chest and spine',
    description: 'Scapular push-ups, a dynamic chest opener, an inchworm and side reaches to get the shoulders ready.', goal: 'general', level: 'intermediate', focus: 'upper',
    parts: [['main', 'off-upper-general-intermediate-a-mobility']], lowImpact: true },
  { id: 'r2j-warmup-lower', category: 'mobility', purpose: 'warmup', name: 'Warm-up · Lower body', subtitle: 'Hips, knees and ankles',
    description: 'Squat and lunge reaches with ankle and knee circles to prepare the legs before squatting or lunging.', goal: 'general', level: 'intermediate', focus: 'lower',
    parts: [['main', 'off-lower-general-intermediate-a-mobility']], lowImpact: true },
  { id: 'r2j-warmup-running', category: 'mobility', purpose: 'warmup', name: 'Warm-up · Before running', subtitle: 'Ankles, hips and quick feet',
    description: 'Ankle and knee circles, a lunge reach and light steps and wall high knees to wake up before a run.', goal: 'general', level: 'intermediate', focus: 'lower',
    parts: [['main', 'off-lower-general-intermediate-b-mobility']] },
  { id: 'r2j-warmup-fullbody', category: 'mobility', purpose: 'warmup', name: 'Warm-up · Full body', subtitle: 'Dynamic · 5 min',
    description: 'Inchworm, squat and lunge reaches, side reaches and knee circles: a quick whole-body warm-up.', goal: 'general', level: 'intermediate', focus: 'fullbody',
    parts: [['main', 'off-fullbody-general-intermediate-b-mobility']], lowImpact: true },
  { id: 'r2j-warmup-shoulders', category: 'mobility', purpose: 'warmup', name: 'Warm-up · Pressing day', subtitle: 'Shoulders and chest',
    description: 'Scapular push-ups, a dynamic chest opener and rear-shoulder and chest stretches before benching or overhead pressing.', goal: 'general', level: 'intermediate', focus: 'upper',
    parts: [['main', 'off-shoulders-general-intermediate-a-mobility']], lowImpact: true },
  { id: 'r2j-warmup-glutes', category: 'mobility', purpose: 'warmup', name: 'Warm-up · Glutes and hips', subtitle: 'Activation before squats and bridges',
    description: 'A marching glute bridge, lunge and squat reaches and a seated glute stretch to switch the glutes on.', goal: 'general', level: 'intermediate', focus: 'lower',
    parts: [['main', 'off-glutes-general-intermediate-a-mobility']], lowImpact: true },
  { id: 'r2j-warmup-strength-10', category: 'mobility', purpose: 'warmup', name: 'Warm-up · Upper and lower, 10 min', subtitle: 'Full strength-day preparation',
    description: 'Both warm-ups in one: scapular and chest work first, then hips, knees and ankles.', goal: 'general', level: 'intermediate', focus: 'fullbody',
    parts: [['main', 'off-shoulders-general-intermediate-a-mobility'], ['main', 'off-lower-general-intermediate-a-mobility']], lowImpact: true },
  { id: 'r2j-cooldown-lower', category: 'mobility', purpose: 'cooldown', name: 'Cool-down · Legs', subtitle: 'Quads, hamstrings, glutes and calves',
    description: 'Four slow holds after a leg day. Nothing forced: stay where it feels like a stretch.', goal: 'general', level: 'intermediate', focus: 'lower',
    parts: [['main', 'off-lower-general-intermediate-c-mobility']], lowImpact: true },
  { id: 'r2j-cooldown-upper', category: 'mobility', purpose: 'cooldown', name: 'Cool-down · Upper body', subtitle: 'Chest, shoulders, triceps and back',
    description: 'Slow stretches after pressing and pulling. Easy range, steady breathing.', goal: 'general', level: 'intermediate', focus: 'upper',
    parts: [['main', 'off-upper-general-intermediate-b-mobility']], lowImpact: true },
  { id: 'r2j-cooldown-quick', category: 'mobility', purpose: 'cooldown', name: 'Cool-down · Quick full body', subtitle: 'Hips, hamstrings, chest and spine',
    description: 'Four moves to wind down after any session when you are short on time.', goal: 'general', level: 'intermediate', focus: 'fullbody',
    parts: [['main', 'off-fullbody-general-intermediate-c-mobility']], lowImpact: true },
  { id: 'r2j-cooldown-fullbody-15', category: 'mobility', purpose: 'cooldown', name: 'Cool-down · Full body, 15 min', subtitle: 'Hips and spine, then lats',
    description: 'The quick cool-down followed by a lat and upper-back sequence for a complete wind-down.', goal: 'general', level: 'intermediate', focus: 'fullbody',
    parts: [['main', 'off-fullbody-general-intermediate-c-mobility'], ['main', 'off-upper-general-beginner-c-mobility']], lowImpact: true },
  { id: 'r2j-mobility-back-hips', category: 'mobility', purpose: 'stretch', name: 'Mobility · Back and hips', subtitle: 'Floor · 10 min',
    description: 'Pelvic tilts, a sphinx, a seated twist and glute and hamstring stretches to loosen up a stiff lower back.', goal: 'general', level: 'beginner', focus: 'fullbody',
    parts: [['main', 'off-back-general-beginner-x-mobility']], lowImpact: true },
  { id: 'r2j-mobility-hips-standing', category: 'mobility', purpose: 'stretch', name: 'Mobility · Hips, standing', subtitle: 'No floor work',
    description: 'The world’s greatest stretch, a lunge reach, a runner’s stretch and a bench quad stretch.', goal: 'general', level: 'beginner', focus: 'lower',
    parts: [['main', 'off-lower-general-beginner-e-mobility']], lowImpact: true },
  { id: 'r2j-stretch-hips-floor', category: 'mobility', purpose: 'stretch', name: 'Stretch · Hips and legs on the floor', subtitle: 'Slow holds · 10 min',
    description: 'Leg-up hamstring, iron cross, side-lying quad, seated glute and butterfly: a slow floor session.', goal: 'general', level: 'beginner', focus: 'lower',
    parts: [['main', 'off-lower-general-beginner-f-mobility']], lowImpact: true },
  { id: 'r2j-stretch-back-body', category: 'mobility', purpose: 'stretch', name: 'Stretch · Back of the body', subtitle: 'Hamstrings, glutes, calves and spine · 10 min',
    description: 'A standing and floor sequence for the whole back of the legs and the lower back.', goal: 'general', level: 'beginner', focus: 'lower',
    parts: [['main', 'off-posterior-general-beginner-x-mobility']], lowImpact: true },
  { id: 'r2j-mobility-neck-shoulders', category: 'mobility', purpose: 'stretch', name: 'Mobility · Neck and shoulders', subtitle: 'A desk-day reset',
    description: 'Gentle neck tilts, an overhead triceps stretch and a lat stretch to let go of the day’s tension.', goal: 'general', level: 'beginner', focus: 'upper',
    parts: [['main', 'off-shoulders-general-beginner-b-mobility']], lowImpact: true },
  { id: 'r2j-stretch-lats', category: 'mobility', purpose: 'stretch', name: 'Stretch · Lats and upper back', subtitle: 'Bench, kneeling and seated',
    description: 'A bench lat stretch, a kneeling lat stretch, an upper-back stretch and a seated twist.', goal: 'general', level: 'beginner', focus: 'upper',
    parts: [['main', 'off-upper-general-beginner-c-mobility']], lowImpact: true },
  { id: 'r2j-stretch-global-20', category: 'mobility', purpose: 'stretch', name: 'Stretch · Global, 20 min', subtitle: 'Legs, upper body and spine',
    description: 'Three slow sequences in a row: legs, chest and shoulders, then hips and legs on the floor. Stay in an easy range.', goal: 'general', level: 'intermediate', focus: 'fullbody',
    parts: [['main', 'off-lower-general-intermediate-c-mobility'], ['main', 'off-upper-general-intermediate-b-mobility'], ['main', 'off-lower-general-beginner-f-mobility']], lowImpact: true },
  { id: 'r2j-stretch-lower-25', category: 'mobility', purpose: 'stretch', name: 'Stretch · Legs and hips, 25 min', subtitle: 'The long leg session',
    description: 'Quads, hamstrings, glutes, calves and adductors in three unhurried sequences, standing and on the floor.', goal: 'general', level: 'intermediate', focus: 'lower',
    parts: [['main', 'off-lower-general-beginner-e-mobility'], ['main', 'off-lower-general-beginner-f-mobility'], ['main', 'off-posterior-general-beginner-x-mobility']], lowImpact: true },
  { id: 'r2j-mobility-full-20', category: 'mobility', purpose: 'stretch', name: 'Mobility · Full body, 20 min', subtitle: 'Standing, floor and seated',
    description: 'A standing flow, a slow floor sequence for hips and legs, and a neck and shoulder finish.', goal: 'general', level: 'beginner', focus: 'fullbody',
    parts: [['main', 'off-fullbody-general-beginner-x-mobility'], ['main', 'off-lower-general-beginner-f-mobility'], ['main', 'off-shoulders-general-beginner-b-mobility']], lowImpact: true },
  { id: 'r2j-stretch-slow-20', category: 'mobility', purpose: 'stretch', name: 'Stretch · Slow holds, 20 min', subtitle: 'Eight stretches · 60 s each',
    description: 'Eight long holds, two rounds: runner’s stretch, triceps, spine twist, lats, hamstring, glute, quad and calf.', goal: 'general', level: 'beginner', focus: 'fullbody',
    parts: [['main', 'off-fullbody-general-beginner-g-mobility']], lowImpact: true },
  { id: 'r2j-recovery-gentle-15', category: 'mobility', purpose: 'recovery', name: 'Recovery · Gentle flow', subtitle: 'Floor, then neck and shoulders',
    description: 'An easy floor sequence for legs, hips and back, then neck and shoulder stretches. For a day off or after a hard week.', goal: 'general', level: 'beginner', focus: 'fullbody',
    parts: [['main', 'off-fullbody-general-beginner-b-mobility'], ['main', 'off-shoulders-general-beginner-b-mobility']], lowImpact: true },
  { id: 'r2j-recovery-long-30', category: 'mobility', purpose: 'recovery', name: 'Recovery · Long flow, 30 min', subtitle: 'Nine holds · three rounds',
    description: 'Hips, upper back, chest, lats, spine, hamstring, glute, quad and calf in three slow rounds. The longest session in the library.', goal: 'general', level: 'intermediate', focus: 'fullbody',
    parts: [['main', 'off-fullbody-general-intermediate-d-mobility']], lowImpact: true },
  { id: 'r2j-hiit-steps-lowimpact', category: 'hiit', name: 'HIIT · Steps and knees', subtitle: 'No jumps · 30 s on / 30 s off',
    description: 'Back-and-forth steps, quick feet, wall high knees and walking knee lunges. Intense without leaving the floor.', goal: 'general', level: 'beginner', focus: 'fullbody',
    parts: [['warmup', 'off-fullbody-general-beginner-a-mobility'], ['main', 'off-fullbody-general-beginner-c-hiit'], ['cooldown', 'off-fullbody-general-beginner-x-mobility']], lowImpact: true },
  { id: 'r2j-hiit-upper-start', category: 'hiit', name: 'HIIT · Upper body', subtitle: 'Push-ups and planks · no jumps',
    description: 'Incline and floor push-ups, scapular push-ups and plank taps in 30/30 intervals.', goal: 'general', level: 'beginner', focus: 'upper',
    parts: [['warmup', 'off-fullbody-general-beginner-a-mobility'], ['main', 'off-upper-general-beginner-a-hiit'], ['cooldown', 'off-fullbody-general-beginner-x-mobility']], lowImpact: true },
  { id: 'r2j-hiit-burpees', category: 'hiit', name: 'HIIT · Burpees and crawls', subtitle: '40 s on / 20 s off · jumps',
    description: 'Jack burpees, star jumps, cross-body climbers and bear crawls: three tough rounds.', goal: 'general', level: 'intermediate', focus: 'fullbody',
    parts: [['warmup', 'off-fullbody-general-intermediate-b-mobility'], ['main', 'off-fullbody-general-intermediate-e-hiit'], ['cooldown', 'off-fullbody-general-intermediate-c-mobility']] },
  { id: 'r2j-hiit-dumbbell-complex', category: 'hiit', name: 'HIIT · Dumbbell complex', subtitle: 'Squat, row, hinge and press on the clock',
    description: 'Goblet squats, one-arm rows, Romanian deadlifts and overhead presses, 40 s each for three rounds.', goal: 'general', level: 'intermediate', focus: 'fullbody',
    parts: [['warmup', 'off-fullbody-general-intermediate-b-mobility'], ['main', 'off-fullbody-general-intermediate-f-hiit'], ['cooldown', 'off-fullbody-general-intermediate-c-mobility']] },
  { id: 'r2j-hiit-plyo-advanced', category: 'hiit', name: 'HIIT · Plyo and burpees', subtitle: '45 s on / 15 s off × 4',
    description: 'Jack burpees, astride jumps, cross-body climbers and jump squats: four hard rounds with a minute between them.', goal: 'general', level: 'advanced', focus: 'fullbody',
    parts: [['warmup', 'off-fullbody-general-intermediate-b-mobility'], ['main', 'off-fullbody-general-advanced-c-hiit'], ['cooldown', 'off-fullbody-general-intermediate-c-mobility']] },
  { id: 'r2j-hiit-treadmill', category: 'hiit', name: 'HIIT · Treadmill 30/30', subtitle: 'Ten fast runs',
    description: 'Ten 30-second runs on the treadmill with 30 seconds of easy walking between them.', goal: 'general', level: 'intermediate', focus: 'cardio',
    parts: [['warmup', 'off-lower-general-intermediate-b-mobility'], ['main', 'off-cardio-general-intermediate-c-hiit'], ['cooldown', 'off-lower-general-intermediate-c-mobility']] },
  { id: 'r2j-hiit-bike-start', category: 'hiit', name: 'HIIT · Bike 30/30', subtitle: 'Eight efforts · low impact',
    description: 'Eight 30-second efforts on the stationary bike with 30 seconds of easy pedalling between them.', goal: 'general', level: 'beginner', focus: 'cardio',
    parts: [['warmup', 'off-fullbody-general-beginner-a-mobility'], ['main', 'off-cardio-general-beginner-a-hiit'], ['cooldown', 'off-fullbody-general-beginner-x-mobility']], lowImpact: true },
  { id: 'r2j-hiit-stepmill', category: 'hiit', name: 'HIIT · Stepmill 30/30', subtitle: 'Eight climbs · low impact',
    description: 'Eight 30-second climbs on the stepmill with 30 seconds easy between them.', goal: 'general', level: 'intermediate', focus: 'cardio',
    parts: [['warmup', 'off-lower-general-intermediate-a-mobility'], ['main', 'off-cardio-general-intermediate-e-hiit'], ['cooldown', 'off-lower-general-intermediate-c-mobility']], lowImpact: true },
  { id: 'r2j-hiit-three-machines', category: 'hiit', name: 'HIIT · Three machines', subtitle: 'Treadmill, stepmill and bike',
    description: 'Ten runs, eight climbs and eight bike efforts: three 30/30 blocks on three machines.', goal: 'general', level: 'intermediate', focus: 'cardio',
    parts: [['warmup', 'off-lower-general-intermediate-b-mobility'], ['main', 'off-cardio-general-intermediate-c-hiit'], ['main', 'off-cardio-general-intermediate-e-hiit'], ['main', 'off-cardio-general-beginner-a-hiit'], ['cooldown', 'off-lower-general-intermediate-c-mobility']] },
  { id: 'r2j-tabata-skierg', category: 'tabata', purpose: 'finisher', name: 'Tabata · SkiErg', subtitle: '20/10 × 8 on the SkiErg',
    description: 'Eight 20-second efforts on the SkiErg with 10 seconds easy between them.', goal: 'general', level: 'intermediate', focus: 'cardio',
    parts: [['warmup', 'off-fullbody-general-beginner-a-mobility'], ['main', 'off-cardio-general-intermediate-a-hiit'], ['cooldown', 'off-fullbody-general-beginner-x-mobility']], lowImpact: true },
  { id: 'r2j-tabata-treadmill', category: 'tabata', purpose: 'finisher', name: 'Tabata · Treadmill sprints', subtitle: '20/10 × 8',
    description: 'Eight 20-second sprints on the treadmill with 10 seconds of walking. For people who already run fast.', goal: 'general', level: 'advanced', focus: 'cardio',
    parts: [['warmup', 'off-lower-general-intermediate-b-mobility'], ['main', 'off-cardio-general-advanced-a-hiit'], ['cooldown', 'off-lower-general-intermediate-c-mobility']] },
  { id: 'r2j-tabata-bike-easy', category: 'tabata', purpose: 'finisher', name: 'Tabata · Bike, first steps', subtitle: 'Easy 20/10 × 8 · low impact',
    description: 'Eight 20-second pushes on the bike at a moderate level, 10 seconds easy between them.', goal: 'general', level: 'beginner', focus: 'cardio',
    parts: [['warmup', 'off-fullbody-general-beginner-a-mobility'], ['main', 'off-cardio-general-beginner-b-hiit'], ['cooldown', 'off-fullbody-general-beginner-x-mobility']], lowImpact: true },
  { id: 'r2j-tabata-three-machines', category: 'tabata', name: 'Tabata · Three machines', subtitle: 'Elliptical, SkiErg and bike',
    description: 'Three 20/10 blocks, eight efforts each, with no impact on the joints.', goal: 'general', level: 'advanced', focus: 'cardio',
    parts: [['warmup', 'off-fullbody-general-beginner-a-mobility'], ['main', 'off-cardio-general-intermediate-x-hiit'], ['main', 'off-cardio-general-intermediate-a-hiit'], ['main', 'off-cardio-general-advanced-x-hiit'], ['cooldown', 'off-fullbody-general-beginner-x-mobility']], lowImpact: true },
  { id: 'r2j-tabata-upper-core', category: 'tabata', name: 'Tabata · Upper body and core', subtitle: 'Push-ups, crawls and plank taps',
    description: 'Two 20/10 blocks: incline push-ups with bear crawls, then plank taps with mountain climbers.', goal: 'general', level: 'intermediate', focus: 'upper',
    parts: [['warmup', 'off-upper-general-intermediate-a-mobility'], ['main', 'off-upper-general-intermediate-x-hiit'], ['main', 'off-abs-general-intermediate-b-hiit'], ['cooldown', 'off-upper-general-intermediate-b-mobility']] },
  { id: 'r2j-intervals-bike-easy', category: 'interval', name: 'Intervals · Bike, easy start', subtitle: '45 s on / 75 s easy',
    description: 'Six 45-second efforts on the bike with long, easy recoveries: the gentlest way into intervals.', goal: 'general', level: 'beginner', focus: 'cardio',
    parts: [['warmup', 'off-fullbody-general-beginner-a-mobility'], ['main', 'off-cardio-general-beginner-a-interval'], ['cooldown', 'off-fullbody-general-beginner-x-mobility']], lowImpact: true },
  { id: 'r2j-intervals-skierg', category: 'interval', name: 'Intervals · SkiErg', subtitle: '40 s on / 20 s easy',
    description: 'Eight 40-second pulls on the SkiErg with 20 seconds easy between them.', goal: 'general', level: 'intermediate', focus: 'cardio',
    parts: [['warmup', 'off-fullbody-general-beginner-a-mobility'], ['main', 'off-cardio-general-intermediate-a-interval'], ['cooldown', 'off-fullbody-general-beginner-x-mobility']], lowImpact: true },
  { id: 'r2j-intervals-treadmill-elliptical', category: 'interval', name: 'Intervals · Treadmill and elliptical', subtitle: '1 min on / 1 min easy · two machines',
    description: 'Eight one-minute runs on the treadmill, then six one-minute pushes on the elliptical.', goal: 'general', level: 'intermediate', focus: 'cardio',
    parts: [['warmup', 'off-lower-general-intermediate-b-mobility'], ['main', 'off-cardio-general-intermediate-b-interval'], ['main', 'off-cardio-general-intermediate-x-interval'], ['cooldown', 'off-lower-general-intermediate-c-mobility']] },
  { id: 'r2j-intervals-skierg-bike-hard', category: 'interval', name: 'Intervals · SkiErg and bike, hard', subtitle: '30/30 and 45/15 × 10',
    description: 'Ten 30-second pulls on the SkiErg, then ten 45-second efforts on the bike with 15 seconds easy.', goal: 'general', level: 'advanced', focus: 'cardio',
    parts: [['warmup', 'off-fullbody-general-intermediate-b-mobility'], ['main', 'off-cardio-general-advanced-a-interval'], ['main', 'off-cardio-general-advanced-b-interval'], ['cooldown', 'off-fullbody-general-intermediate-c-mobility']], lowImpact: true },
  { id: 'r2j-intervals-elliptical-cross', category: 'interval', name: 'Intervals · Elliptical and cross trainer', subtitle: '4 min and 3 min on · steady',
    description: 'Four four-minute blocks on the elliptical, then five three-minute blocks on the cross trainer. Aerobic and low impact.', goal: 'endurance', level: 'intermediate', focus: 'cardio',
    parts: [['warmup', 'off-fullbody-general-beginner-a-mobility'], ['main', 'off-cardio-endurance-beginner-a-interval'], ['main', 'off-cardio-endurance-intermediate-a-interval'], ['cooldown', 'off-fullbody-general-beginner-x-mobility']], lowImpact: true },
  { id: 'r2j-intervals-stepmill-incline', category: 'interval', name: 'Intervals · Stepmill and incline walk', subtitle: '90 s hard climbs, then 3 min walks',
    description: 'Eight hard 90-second climbs on the stepmill, then four three-minute incline walks to finish.', goal: 'endurance', level: 'advanced', focus: 'cardio',
    parts: [['warmup', 'off-lower-general-intermediate-a-mobility'], ['main', 'off-cardio-endurance-advanced-a-interval'], ['main', 'off-cardio-endurance-beginner-x-interval'], ['cooldown', 'off-lower-general-intermediate-c-mobility']], lowImpact: true },
  { id: 'r2j-core-hiit', category: 'core', name: 'Core · HIIT', subtitle: '40 s on / 20 s off · floor',
    description: 'Flutter kicks, cross-body climbers, plank taps and Russian twists: three rounds for the whole trunk.', goal: 'general', level: 'intermediate', focus: 'core',
    parts: [['warmup', 'off-fullbody-general-intermediate-b-mobility'], ['main', 'off-abs-general-intermediate-c-hiit']] },
  { id: 'r2j-circuit-home-full', category: 'circuit', name: 'Circuit · Home, full body', subtitle: 'Bodyweight · 3 rounds',
    description: 'Walking lunges, incline push-ups, glute bridges, dead bugs and a side plank. All you need is a bench or a sturdy step for the push-ups.', goal: 'general', level: 'beginner', focus: 'fullbody',
    parts: [['warmup', 'off-fullbody-general-beginner-a-mobility'], ['main', 'off-fullbody-general-beginner-b-circuit'], ['cooldown', 'off-fullbody-general-beginner-x-mobility']] },
  { id: 'r2j-circuit-legs-bodyweight', category: 'circuit', name: 'Circuit · Legs and glutes, no equipment', subtitle: 'Bodyweight · 3 rounds',
    description: 'Split squats, marching bridges, side hip abductions and curtsy lunges, then slow hip stretches on the floor.', goal: 'general', level: 'beginner', focus: 'lower',
    parts: [['warmup', 'off-lower-general-beginner-b-mobility'], ['main', 'off-lower-general-beginner-a-circuit'], ['cooldown', 'off-lower-general-beginner-c-mobility']] },
  { id: 'r2j-mixed-upper-stepmill-50', category: 'mixed', name: 'Strength + cardio · Upper body and stepmill', subtitle: 'Straight sets, then 30/30 climbs',
    description: 'An upper-body strength block with prescribed rest, then eight 30-second climbs on the stepmill to finish.', goal: 'general', level: 'intermediate', focus: 'fullbody',
    parts: [['warmup', 'off-upper-general-intermediate-a-mobility'], ['main', 'off-upper-general-intermediate-x'], ['main', 'off-cardio-general-intermediate-e-hiit'], ['cooldown', 'off-fullbody-general-intermediate-c-mobility']] },
  { id: 'r2j-mixed-fullbody-treadmill-60', category: 'mixed', name: 'Strength + cardio · Full body and treadmill, 60 min', subtitle: 'The complete hour',
    description: 'Warm-up, a full-body strength block, eight one-minute runs on the treadmill and a cool-down.', goal: 'general', level: 'intermediate', focus: 'fullbody',
    parts: [['warmup', 'off-upper-general-intermediate-a-mobility'], ['main', 'off-fullbody-general-intermediate-a'], ['main', 'off-cardio-general-intermediate-b-interval'], ['cooldown', 'off-upper-general-intermediate-b-mobility']] },
  { id: 'r2j-mixed-lower-skierg-50', category: 'mixed', name: 'Strength + cardio · Lower body and SkiErg', subtitle: 'Straight sets, then a Tabata finisher',
    description: 'A lower-body strength block, then eight 20/10 efforts on the SkiErg to finish.', goal: 'general', level: 'intermediate', focus: 'lower',
    parts: [['warmup', 'off-lower-general-intermediate-a-mobility'], ['main', 'off-lower-general-intermediate-x'], ['main', 'off-cardio-general-intermediate-a-hiit'], ['cooldown', 'off-lower-general-intermediate-c-mobility']] },
  { id: 'r2j-mixed-push-bike-50', category: 'mixed', name: 'Strength + cardio · Push and bike', subtitle: 'Straight sets, then 30/30 on the bike',
    description: 'Chest, shoulders and triceps with prescribed rest, then eight 30-second efforts on the bike.', goal: 'general', level: 'intermediate', focus: 'upper',
    parts: [['warmup', 'off-upper-general-intermediate-a-mobility'], ['main', 'off-push-general-intermediate-x'], ['main', 'off-cardio-general-beginner-a-hiit'], ['cooldown', 'off-upper-general-intermediate-b-mobility']] },
  { id: 'r2j-s-chest-hypertrophy-beginner-a', category: 'strength', name: 'Chest · Novice A', subtitle: 'Hypertrophy · Stable',
    description: 'Presses and flies for the chest on stable machines and cables. A short warm-up first, then straight sets with generous rest.', goal: 'hypertrophy', level: 'beginner', focus: 'upper',
    parts: [['warmup', 'off-fullbody-general-beginner-a-mobility'], ['main', 'off-chest-hypertrophy-beginner-a']] },
  { id: 'r2j-s-chest-hypertrophy-beginner-b', category: 'strength', name: 'Chest · Novice B', subtitle: 'Hypertrophy · Mixed',
    description: 'Presses and flies for the chest mixing machines and free weights. A short warm-up first, then straight sets with generous rest.', goal: 'hypertrophy', level: 'beginner', focus: 'upper',
    parts: [['warmup', 'off-fullbody-general-beginner-a-mobility'], ['main', 'off-chest-hypertrophy-beginner-b']] },
  { id: 'r2j-s-back-hypertrophy-beginner-a', category: 'strength', name: 'Back muscles · Novice A', subtitle: 'Hypertrophy · Stable',
    description: 'Pulls and rows for the back on stable machines and cables. A short warm-up first, then straight sets with generous rest.', goal: 'hypertrophy', level: 'beginner', focus: 'upper',
    parts: [['warmup', 'off-fullbody-general-beginner-a-mobility'], ['main', 'off-back-hypertrophy-beginner-a']] },
  { id: 'r2j-s-back-hypertrophy-beginner-b', category: 'strength', name: 'Back muscles · Novice B', subtitle: 'Hypertrophy · Mixed',
    description: 'Pulls and rows for the back mixing machines and free weights. A short warm-up first, then straight sets with generous rest.', goal: 'hypertrophy', level: 'beginner', focus: 'upper',
    parts: [['warmup', 'off-fullbody-general-beginner-a-mobility'], ['main', 'off-back-hypertrophy-beginner-b']] },
  { id: 'r2j-s-shoulders-hypertrophy-beginner-a', category: 'strength', name: 'Shoulders · Novice A', subtitle: 'Hypertrophy · Stable',
    description: 'Presses and raises for the shoulders on stable machines and cables. A short warm-up first, then straight sets with generous rest.', goal: 'hypertrophy', level: 'beginner', focus: 'upper',
    parts: [['warmup', 'off-fullbody-general-beginner-a-mobility'], ['main', 'off-shoulders-hypertrophy-beginner-a']] },
  { id: 'r2j-s-shoulders-hypertrophy-beginner-b', category: 'strength', name: 'Shoulders · Novice B', subtitle: 'Hypertrophy · Free weights',
    description: 'Presses and raises for the shoulders with free weights. A short warm-up first, then straight sets with generous rest.', goal: 'hypertrophy', level: 'beginner', focus: 'upper',
    parts: [['warmup', 'off-fullbody-general-beginner-a-mobility'], ['main', 'off-shoulders-hypertrophy-beginner-b']] },
  { id: 'r2j-s-arms-hypertrophy-beginner-x', category: 'strength', name: 'Arms · Novice', subtitle: 'Hypertrophy · Stable',
    description: 'Curls and extensions for the arms on stable machines and cables. A short warm-up first, then straight sets with generous rest.', goal: 'hypertrophy', level: 'beginner', focus: 'upper',
    parts: [['warmup', 'off-fullbody-general-beginner-a-mobility'], ['main', 'off-arms-hypertrophy-beginner-x']] },
  { id: 'r2j-s-quads-hypertrophy-beginner-a', category: 'strength', name: 'Quads · Novice A', subtitle: 'Hypertrophy · Stable',
    description: 'Squat and press patterns for the quads on stable machines and cables. A short warm-up first, then straight sets with generous rest.', goal: 'hypertrophy', level: 'beginner', focus: 'lower',
    parts: [['warmup', 'off-lower-general-beginner-b-mobility'], ['main', 'off-quads-hypertrophy-beginner-a']] },
  { id: 'r2j-s-quads-hypertrophy-beginner-b', category: 'strength', name: 'Quads · Novice B', subtitle: 'Hypertrophy · Mixed',
    description: 'Squat and press patterns for the quads mixing machines and free weights. A short warm-up first, then straight sets with generous rest.', goal: 'hypertrophy', level: 'beginner', focus: 'lower',
    parts: [['warmup', 'off-lower-general-beginner-b-mobility'], ['main', 'off-quads-hypertrophy-beginner-b']] },
  { id: 'r2j-s-hamstrings-hypertrophy-beginner-x', category: 'strength', name: 'Hamstrings · Novice', subtitle: 'Hypertrophy · Stable',
    description: 'Hinges and curls for the hamstrings on stable machines and cables. A short warm-up first, then straight sets with generous rest.', goal: 'hypertrophy', level: 'beginner', focus: 'lower',
    parts: [['warmup', 'off-lower-general-beginner-b-mobility'], ['main', 'off-hamstrings-hypertrophy-beginner-x']] },
  { id: 'r2j-s-glutes-hypertrophy-beginner-b', category: 'strength', name: 'Glutes · Novice B', subtitle: 'Hypertrophy · Mixed',
    description: 'Bridges, hinges and abduction for the glutes mixing machines and free weights. A short warm-up first, then straight sets with generous rest.', goal: 'hypertrophy', level: 'beginner', focus: 'lower',
    parts: [['warmup', 'off-lower-general-beginner-b-mobility'], ['main', 'off-glutes-hypertrophy-beginner-b']] },
  { id: 'r2j-s-glutes-hypertrophy-beginner-c', category: 'strength', name: 'Glutes · Novice C', subtitle: 'Hypertrophy · Unilateral',
    description: 'Bridges, hinges and abduction for the glutes working one side at a time. A short warm-up first, then straight sets with generous rest.', goal: 'hypertrophy', level: 'beginner', focus: 'lower',
    parts: [['warmup', 'off-lower-general-beginner-b-mobility'], ['main', 'off-glutes-hypertrophy-beginner-c']] },
  { id: 'r2j-s-chest-hypertrophy-intermediate-a', category: 'strength', name: 'Chest · Intermediate A', subtitle: 'Hypertrophy · Tension',
    description: 'Presses and flies for the chest with a focus on time under tension. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'hypertrophy', level: 'intermediate', focus: 'upper',
    parts: [['warmup', 'off-upper-general-intermediate-a-mobility'], ['main', 'off-chest-hypertrophy-intermediate-a'], ['cooldown', 'off-upper-general-intermediate-b-mobility']] },
  { id: 'r2j-s-chest-hypertrophy-intermediate-b', category: 'strength', name: 'Chest · Intermediate B', subtitle: 'Hypertrophy · Mixed',
    description: 'Presses and flies for the chest mixing machines and free weights. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'hypertrophy', level: 'intermediate', focus: 'upper',
    parts: [['warmup', 'off-upper-general-intermediate-a-mobility'], ['main', 'off-chest-hypertrophy-intermediate-b'], ['cooldown', 'off-upper-general-intermediate-b-mobility']] },
  { id: 'r2j-s-chest-hypertrophy-intermediate-c', category: 'strength', name: 'Chest · Intermediate C', subtitle: 'Hypertrophy · Upper chest',
    description: 'Presses and flies for the chest with an upper-chest emphasis. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'hypertrophy', level: 'intermediate', focus: 'upper',
    parts: [['warmup', 'off-upper-general-intermediate-a-mobility'], ['main', 'off-chest-hypertrophy-intermediate-c'], ['cooldown', 'off-upper-general-intermediate-b-mobility']] },
  { id: 'r2j-s-back-hypertrophy-intermediate-a', category: 'strength', name: 'Back muscles · Intermediate A', subtitle: 'Hypertrophy · Tension',
    description: 'Pulls and rows for the back with a focus on time under tension. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'hypertrophy', level: 'intermediate', focus: 'upper',
    parts: [['warmup', 'off-upper-general-intermediate-a-mobility'], ['main', 'off-back-hypertrophy-intermediate-a'], ['cooldown', 'off-upper-general-intermediate-b-mobility']] },
  { id: 'r2j-s-back-hypertrophy-intermediate-b', category: 'strength', name: 'Back muscles · Intermediate B', subtitle: 'Hypertrophy · Mixed',
    description: 'Pulls and rows for the back mixing machines and free weights. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'hypertrophy', level: 'intermediate', focus: 'upper',
    parts: [['warmup', 'off-upper-general-intermediate-a-mobility'], ['main', 'off-back-hypertrophy-intermediate-b'], ['cooldown', 'off-upper-general-intermediate-b-mobility']] },
  { id: 'r2j-s-shoulders-hypertrophy-intermediate-a', category: 'strength', name: 'Shoulders · Intermediate A', subtitle: 'Hypertrophy · Tension',
    description: 'Presses and raises for the shoulders with a focus on time under tension. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'hypertrophy', level: 'intermediate', focus: 'upper',
    parts: [['warmup', 'off-upper-general-intermediate-a-mobility'], ['main', 'off-shoulders-hypertrophy-intermediate-a'], ['cooldown', 'off-upper-general-intermediate-b-mobility']] },
  { id: 'r2j-s-shoulders-hypertrophy-intermediate-b', category: 'strength', name: 'Shoulders · Intermediate B', subtitle: 'Hypertrophy · Machines',
    description: 'Presses and raises for the shoulders on machines. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'hypertrophy', level: 'intermediate', focus: 'upper',
    parts: [['warmup', 'off-upper-general-intermediate-a-mobility'], ['main', 'off-shoulders-hypertrophy-intermediate-b'], ['cooldown', 'off-upper-general-intermediate-b-mobility']] },
  { id: 'r2j-s-arms-hypertrophy-intermediate-a', category: 'strength', name: 'Arms · Intermediate A', subtitle: 'Hypertrophy · Free weights',
    description: 'Curls and extensions for the arms with free weights. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'hypertrophy', level: 'intermediate', focus: 'upper',
    parts: [['warmup', 'off-upper-general-intermediate-a-mobility'], ['main', 'off-arms-hypertrophy-intermediate-a'], ['cooldown', 'off-upper-general-intermediate-b-mobility']] },
  { id: 'r2j-s-arms-hypertrophy-intermediate-b', category: 'strength', name: 'Arms · Intermediate B', subtitle: 'Hypertrophy · Machines',
    description: 'Curls and extensions for the arms on machines. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'hypertrophy', level: 'intermediate', focus: 'upper',
    parts: [['warmup', 'off-upper-general-intermediate-a-mobility'], ['main', 'off-arms-hypertrophy-intermediate-b'], ['cooldown', 'off-upper-general-intermediate-b-mobility']] },
  { id: 'r2j-s-quads-hypertrophy-intermediate-a', category: 'strength', name: 'Quads · Intermediate A', subtitle: 'Hypertrophy · Tension',
    description: 'Squat and press patterns for the quads with a focus on time under tension. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'hypertrophy', level: 'intermediate', focus: 'lower',
    parts: [['warmup', 'off-lower-general-intermediate-a-mobility'], ['main', 'off-quads-hypertrophy-intermediate-a'], ['cooldown', 'off-lower-general-intermediate-c-mobility']] },
  { id: 'r2j-s-quads-hypertrophy-intermediate-b', category: 'strength', name: 'Quads · Intermediate B', subtitle: 'Hypertrophy · Machines',
    description: 'Squat and press patterns for the quads on machines. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'hypertrophy', level: 'intermediate', focus: 'lower',
    parts: [['warmup', 'off-lower-general-intermediate-a-mobility'], ['main', 'off-quads-hypertrophy-intermediate-b'], ['cooldown', 'off-lower-general-intermediate-c-mobility']] },
  { id: 'r2j-s-hamstrings-hypertrophy-intermediate-a', category: 'strength', name: 'Hamstrings · Intermediate A', subtitle: 'Hypertrophy · Hip dominant',
    description: 'Hinges and curls for the hamstrings led by the hips. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'hypertrophy', level: 'intermediate', focus: 'lower',
    parts: [['warmup', 'off-lower-general-intermediate-a-mobility'], ['main', 'off-hamstrings-hypertrophy-intermediate-a'], ['cooldown', 'off-lower-general-intermediate-c-mobility']] },
  { id: 'r2j-s-glutes-hypertrophy-intermediate-a', category: 'strength', name: 'Glutes · Intermediate A', subtitle: 'Hypertrophy · Tension',
    description: 'Bridges, hinges and abduction for the glutes with a focus on time under tension. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'hypertrophy', level: 'intermediate', focus: 'lower',
    parts: [['warmup', 'off-glutes-general-intermediate-a-mobility'], ['main', 'off-glutes-hypertrophy-intermediate-a'], ['cooldown', 'off-lower-general-intermediate-c-mobility']] },
  { id: 'r2j-s-posterior-hypertrophy-intermediate-x', category: 'strength', name: 'Posterior chain · Intermediate', subtitle: 'Hypertrophy · Mixed',
    description: 'Hinges, bridges and curls for the back of the legs mixing machines and free weights. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'hypertrophy', level: 'intermediate', focus: 'lower',
    parts: [['warmup', 'off-lower-general-intermediate-a-mobility'], ['main', 'off-posterior-hypertrophy-intermediate-x'], ['cooldown', 'off-lower-general-intermediate-c-mobility']] },
  { id: 'r2j-s-upper-general-intermediate-x', category: 'strength', name: 'Upper body · Intermediate', subtitle: 'General · Free weights',
    description: 'Pushing and pulling for the whole upper body with free weights. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'general', level: 'intermediate', focus: 'upper',
    parts: [['warmup', 'off-upper-general-intermediate-a-mobility'], ['main', 'off-upper-general-intermediate-x'], ['cooldown', 'off-upper-general-intermediate-b-mobility']] },
  { id: 'r2j-s-lower-general-intermediate-x', category: 'strength', name: 'Lower body · Intermediate', subtitle: 'General · Free weights',
    description: 'Squats, hinges and calves for the legs with free weights. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'general', level: 'intermediate', focus: 'lower',
    parts: [['warmup', 'off-lower-general-intermediate-a-mobility'], ['main', 'off-lower-general-intermediate-x'], ['cooldown', 'off-lower-general-intermediate-c-mobility']] },
  { id: 'r2j-s-chest-hypertrophy-advanced-a', category: 'strength', name: 'Chest · Advanced A', subtitle: 'Hypertrophy · Heavy',
    description: 'Presses and flies for the chest with heavier loads and longer rests. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'hypertrophy', level: 'advanced', focus: 'upper',
    parts: [['warmup', 'off-upper-general-intermediate-a-mobility'], ['main', 'off-chest-hypertrophy-advanced-a'], ['cooldown', 'off-upper-general-intermediate-b-mobility']] },
  { id: 'r2j-s-back-hypertrophy-advanced-a', category: 'strength', name: 'Back muscles · Advanced A', subtitle: 'Hypertrophy · Heavy',
    description: 'Pulls and rows for the back with heavier loads and longer rests. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'hypertrophy', level: 'advanced', focus: 'upper',
    parts: [['warmup', 'off-upper-general-intermediate-a-mobility'], ['main', 'off-back-hypertrophy-advanced-a'], ['cooldown', 'off-upper-general-intermediate-b-mobility']] },
  { id: 'r2j-s-shoulders-hypertrophy-advanced-a', category: 'strength', name: 'Shoulders · Advanced A', subtitle: 'Hypertrophy · Heavy',
    description: 'Presses and raises for the shoulders with heavier loads and longer rests. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'hypertrophy', level: 'advanced', focus: 'upper',
    parts: [['warmup', 'off-upper-general-intermediate-a-mobility'], ['main', 'off-shoulders-hypertrophy-advanced-a'], ['cooldown', 'off-upper-general-intermediate-b-mobility']] },
  { id: 'r2j-s-quads-hypertrophy-advanced-b', category: 'strength', name: 'Quads · Advanced B', subtitle: 'Hypertrophy · Free weights',
    description: 'Squat and press patterns for the quads with free weights. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'hypertrophy', level: 'advanced', focus: 'lower',
    parts: [['warmup', 'off-lower-general-intermediate-a-mobility'], ['main', 'off-quads-hypertrophy-advanced-b'], ['cooldown', 'off-lower-general-intermediate-c-mobility']] },
  { id: 'r2j-s-glutes-hypertrophy-advanced-b', category: 'strength', name: 'Glutes · Advanced B', subtitle: 'Hypertrophy · Heavy',
    description: 'Bridges, hinges and abduction for the glutes with heavier loads and longer rests. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'hypertrophy', level: 'advanced', focus: 'lower',
    parts: [['warmup', 'off-glutes-general-intermediate-a-mobility'], ['main', 'off-glutes-hypertrophy-advanced-b'], ['cooldown', 'off-lower-general-intermediate-c-mobility']] },
  { id: 'r2j-s-hamstrings-hypertrophy-advanced-a', category: 'strength', name: 'Hamstrings · Advanced A', subtitle: 'Hypertrophy · Tension',
    description: 'Hinges and curls for the hamstrings with a focus on time under tension. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'hypertrophy', level: 'advanced', focus: 'lower',
    parts: [['warmup', 'off-lower-general-intermediate-a-mobility'], ['main', 'off-hamstrings-hypertrophy-advanced-a'], ['cooldown', 'off-lower-general-intermediate-c-mobility']] },
  { id: 'r2j-s-lower-hypertrophy-advanced-x', category: 'strength', name: 'Lower body · Advanced', subtitle: 'Hypertrophy · Heavy',
    description: 'Squats, hinges and calves for the legs with heavier loads and longer rests. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'hypertrophy', level: 'advanced', focus: 'lower',
    parts: [['warmup', 'off-lower-general-intermediate-a-mobility'], ['main', 'off-lower-hypertrophy-advanced-x'], ['cooldown', 'off-lower-general-intermediate-c-mobility']] },
  { id: 'r2j-s-fullbody-hypertrophy-advanced-x', category: 'strength', name: 'Full body · Advanced', subtitle: 'Hypertrophy · Heavy',
    description: 'A balanced session for the whole body with heavier loads and longer rests. Dynamic warm-up, the main block with prescribed sets and rest, and a cool-down.', goal: 'hypertrophy', level: 'advanced', focus: 'fullbody',
    parts: [['warmup', 'off-fullbody-general-intermediate-b-mobility'], ['main', 'off-fullbody-hypertrophy-advanced-x']] },
]

// Collections organise the catalogue (they are not multi-week programs). `auto` resolves at build
// time into a fixed, reviewable list (admins can still edit membership afterwards).
export const COLLECTIONS = [
  { id: 'c2j-start', name: 'Start here', description: 'Short, clear sessions to get to know guided training.', style: 'start',
    routineIds: ['r2j-tabata-start', 'r2j-hiit-lowimpact', 'r2j-circuit-machines-start', 'r2j-circuit-bodyweight', 'r2j-intervals-bike-start', 'r2j-core-start', 'r2j-mobility-fullbody'] },
  { id: 'c2j-tabata', name: '2J Tabata', description: 'The 20/10 format, from first steps to advanced.', style: 'tabata', auto: { category: 'tabata' } },
  { id: 'c2j-hiit', name: '2J HIIT', description: 'Hard intervals with their own work and rest.', style: 'hiit', auto: { category: ['hiit', 'mixed'] } },
  { id: 'c2j-circuits', name: '2J Circuits', description: 'Stations one after another: machines, dumbbells or no equipment.', style: 'circuit', auto: { category: ['circuit', 'core'] } },
  { id: 'c2j-cardio', name: '2J Cardio', description: 'Intervals on the bike, elliptical, stepmill and treadmill.', style: 'interval',
    auto: { category: 'interval' }, extra: ['r2j-tabata-bike', 'r2j-tabata-elliptical', 'r2j-hiit-machines'] },
  { id: 'c2j-mobility', name: '2J Mobility', description: 'Move better before or after training.', style: 'mobility', auto: { category: 'mobility' } },
  { id: 'c2j-strength', name: '2J Strength', description: 'Straight-set strength and hypertrophy, from first steps to splits.', style: 'strength', auto: { category: 'strength' } },
  { id: 'c2j-express', name: '2J Express', description: 'For when you have ten minutes.', style: 'express', auto: { maxMinutes: 10, notCategory: 'mobility' } },
  { id: 'c2j-warmup', name: 'Warm-ups', description: 'Get ready in five minutes: upper, lower, glutes, running or the whole body.', style: 'mobility', auto: { purpose: 'warmup' } },
  { id: 'c2j-cooldown', name: 'Cool-down and stretching', description: 'Wind down after training or stretch on a rest day, from five to twenty-five minutes.', style: 'mobility', auto: { purpose: ['cooldown', 'stretch'] } },
  { id: 'c2j-recovery', name: 'Recovery', description: 'Easy flows for the day after a hard session or a week off.', style: 'mobility', auto: { purpose: 'recovery' } },
  { id: 'c2j-finishers', name: 'Finishers', description: 'Short machine bursts to finish a strength day.', style: 'express', auto: { purpose: 'finisher' } },
  { id: 'c2j-home', name: 'Home and hotel', description: 'Only your body: sessions for home, a hotel or a park.', style: 'start', auto: { tag: 'no-equipment' } },
  { id: 'c2j-lowimpact', name: 'Low impact', description: 'No jumps and no running: kind to knees and joints.', style: 'interval', auto: { tag: 'low-impact' } },
  { id: 'c2j-long', name: 'Thirty minutes or more', description: 'When you have time: full strength days and long flows.', style: 'strength', auto: { minMinutes: 30 } },
]

// Editorial picks for the hero, in order (admins can change them).
export const FEATURED = ['r2j-tabata-fullbody', 'r2j-mobility-hips', 'r2j-hiit-lowimpact']
